server:
  port: 8080
spring:
  jpa:
    open-in-view: false
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddlAuto: none

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/fitness_blog
    username: root

  cloud:
    config:
      uri: http://configClient:configClient@localhost:8090
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
allowOrigin: http://localhost
