server:
  port: 8080

db:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/fitness_blog
  username: postgres
  password: root

eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://configClient:configClient@localhost:8090/eureka/
    
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    
allowOrigin: http://localhost

spring:
  flyway:
    locations: "classpath:db/migration"
