server:
  port: 8070
  
spring:    
  jpa:
    open-in-view: false
    database: postgresql
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  datasource:
    platform: postgres
    username: postgres
    driverClassName: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/users

eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://configClient:configClient@localhost:8090/eureka/
    
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    
allowOrigin: http://localhost
