server:
  port: 8100

eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://configClient:configClient@localhost:8090/eureka/
      
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
        
      routes:
      - id: article-service
        uri: lb://article-service
        predicates: 
        - Path=/article/**
        filters: 
        - RewritePath=/article/(?<path>.*), /$\{path}
        
      - id: auth-service
        uri: lb://auth-service
        predicates: 
        - Path=/auth/**
        filters: 
        - RewritePath=/auth/(?<path>.*), /$\{path}

        - id: video-service
        uri: lb://video-service
        predicates: 
        - Path=/video/**
        filters: 
        - RewritePath=/video/(?<path>.*), /$\{path}

        - id: chat-service
        uri: lb://chat-service
        predicates: 
        - Path=/chat/**
        filters: 
        - RewritePath=/chat, /
        
