server:
  port: 8100

eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://configClient:configClient@localhost:8090/eureka/
      
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
        
      routes:
      - id: article_service
        uri: lb://article_service
        predicates: 
        - Path=/article/**
        filters: 
        - RewritePath=/article/(?<path>.*), /$\{path}
        
      - id: auth_service
        uri: lb://auth_service
        predicates: 
        - Path=/auth/**
        filters: 
        - RewritePath=/auth/(?<path>.*), /$\{path}
